- repo: https://github.com/UCD-DART/prettier-plugin-php-pre-commit
  rev: master
  hooks:
    - id: prettier
      args: [--check]
      files: ^(includes|migrations|src|tests|themes|translations)/.+\.(php|js|ts|tsx|css|scss|html)$
