repos:
- repo: https://github.com/budziam/prettier-plugin-php-pre-commit
  rev: 178470678802a55c97f7c5101574434fb90d228b
  hooks:
    - id: prettier
      args: [--check]
      files: ^(includes|migrations|src|tests|themes|translations)/.+\.(php|js|ts|tsx|css|scss|html)$
