repos:
- repo: https://github.com/budziam/prettier-plugin-php-pre-commit
  rev: 52e9ead5311816504a590d5bf0c422f1d3091a38
  hooks:
    - id: prettier
      args: [--write]
      files: ^(includes|migrations|src|tests|themes|translations)/.+\.(php|js|ts|tsx|css|scss|html)$
