name: CI workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  static_code_analysis:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: pip install pre-commit
      - run: pre-commit run --all-files --show-diff-on-failure

  frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
        env:
          NODE_ENV: production

  backend:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php_version: "8.0"
            composer_file: "composer-v8.0.json"
          - php_version: "8.1"
            composer_file: "composer.json"
          - php_version: "8.2"
            composer_file: "composer.json"
          - php_version: "8.3"
            composer_file: "composer.json"
          - php_version: "8.4"
            composer_file: "composer.json"
          - php_version: "8.5"
            composer_file: "composer.json"
          - php_version: "8.6"
            composer_file: "composer.json"
    env:
      APP_DEBUG: true
      DB_HOST: 127.0.0.1
      DB_DATABASE: sklep_sms_test
      DB_USERNAME: root
      DB_PASSWORD: secret
    services:
      mysql:
        image: mysql:5.5
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_DATABASE: sklep_sms_test
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - run: sudo /etc/init.d/mysql start

      - name: Setup PHP ${{ matrix.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: mysqli
          coverage: xdebug

      - name: Install dependencies
        if: matrix.composer_file == 'composer.json'
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--optimize-autoloader"

      - name: Install dependencies (PHP 8.0)
        if: matrix.composer_file != 'composer.json'
        env:
          COMPOSER: ${{ matrix.composer_file }}
        run: composer install --optimize-autoloader --no-interaction

      - name: Transpile to PHP ${{ matrix.php_version }}
        run: |
          docker run \
          --rm \
          --env PHP_VERSION=${{ matrix.php_version }} \
          -v $(pwd):/project \
          budziam/rector:2.5.8 \
          process \
          /project/includes \
          /project/tests \
          --config /project/rector.php

      - run: php artisan test:setup
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Run tests
        run: ./vendor/bin/phpunit --coverage-clover clover.xml --testdox
        env:
          XDEBUG_MODE: coverage
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Upload coverage results to Coveralls
        if: matrix.php_version == '8.2'
        uses: coverallsapp/github-action@v2
        with:
          file: clover.xml
